# Generated by Django 6.0.2 on 2026-04-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='auth_source',
            field=models.CharField(choices=[('local', 'Local'), ('google', 'Google'), ('github', 'GitHub')], default='local', max_length=20),
        ),
    ]
